catBreeds = [
    "abyssinian",
    "american bobtail",
    "american curl",
    "american shorthair",
    "american wirehair",
    "balinese",
    "bengal",
    "birman",
    "bombay",
    "british shorthair",
    "burmese",
    "chartreux",
    "cornish rex",
    "devon rex",
    "egyptian mau",
    "european burmese",
    "exotic shorthair",
    "havana brown",
    "himalayan",
    "japanese bobtail",
    "korat",
    "maine coon",
    "manx",
    "norwegian forest",
    "ocicat",
    "oriental shorthair",
    "persian",
    "pixie-bob",
    "ragamuffin",
    "ragdoll",
    "russian blue",
    "scottish fold",
    "siamese",
    "siberian",
    "singapura",
    "somali",
    "sphynx",
    "tonkinese",
    "turkish angora",
    "turkish van",
]